FROM mcr.microsoft.com/dotnet/aspnet:6.0-focal AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0-focal AS build
WORKDIR /src
COPY . .
RUN dotnet build -c Release -o /app/build

FROM base AS final
WORKDIR /app
EXPOSE 80
COPY --from=build /app/build .

ENTRYPOINT ["dotnet", "TRPO_Web_start.dll"]